package uk.co.louiseconnell.quarkus.panache.model;

public enum Language {
  ENGLISH, FRENCH, SPANISH, GERMAN, ITALIAN, FINNISH, SWEDISH, NORWEGIAN, RUSSIAN, POLISH, JAPANESE, CHINESE, HINDI, ARABIC, PORTUGUESE, DUTCH, BENGALI, PUNJABI, TURKISH, CZECH, UKRAINIAN, KOREAN, ROMANIAN, GREEK, HUNGARIAN, DANISH,
  PERSIAN, MALAY, THAI, INDONESIAN, HEBREW, VIETNAMESE, URDU, TAMIL, LATVIAN, LITHUANIAN, SLOVAK, SLOVENIAN, BULGARIAN, CROATIAN, ESTONIAN, ICELANDIC, MALTESE
}
